pipeline:
  analyze:
    image: ghcr.io/cirruslabs/flutter:stable
    commands:
      - flutter pub get
      - flutter analyze --no-fatal-infos

  test:
    image: ghcr.io/cirruslabs/flutter:stable
    commands:
      - flutter pub get
      - flutter test

  build-web:
    image: ghcr.io/cirruslabs/flutter:stable
    commands:
      - flutter pub get
      - flutter build web --release
    artifacts:
      - build/web/**
    when:
      branch: [main, develop]

  build-linux:
    image: ghcr.io/cirruslabs/flutter:stable
    commands:
      - apt-get update -y
      - apt-get install -y cmake ninja-build clang libgtk-3-dev
      - flutter pub get
      - flutter build linux --release
    artifacts:
      - build/linux/x64/release/bundle/**
    when:
      branch: [main, develop]
